
//FETCH CATEGORY
export const FETCH_CATEGORIES = 'category/FETCH_CATEGORIES'
export const FETCH_CATEGORIES_SUCCESS = 'category/FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILED = 'category/FETCH_CATEGORIES_FAILED'

//CREATE OR UPDATE CATEGORY
export const SAVE_CATEGORY = 'category/SAVE_CATEGORY'
export const SAVE_CATEGORY_SUCCESS = 'category/SAVE_CATEGORY_SUCCESS'
export const SAVE_CATEGORY_FAILED = 'category/SAVE_CATEGORY_FAILED'

//DELETE CATEGORY
export const DELETE_CATEGORY = 'category/DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'category/DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILED = 'category/DELETE_CATEGORY_FAILED'


//SELECT CATEGORY
export const SELECT_CATEGORY = 'category/SELECT_CATEGORY'