/**
 * REDUCERS
 */

//FETCH SETTING
export const FETCH_SETTINGS = 'SETTING/FETCH_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = 'SETTING/FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_FAILED = 'SETTING/FETCH_SETTINGS_FAILED'

//CREATE OR UPDATE SETTING
export const SAVE_SETTING = 'SETTING/SAVE_SETTING'
export const SAVE_SETTING_SUCCESS = 'SETTING/SAVE_SETTING_SUCCESS'
export const SAVE_SETTING_FAILED = 'SETTING/SAVE_SETTING_FAILED'