/**
 * REDUCERS
 */
//FETCH CUSTOMER
export const FETCH_CUSTOMERS = 'CUSTOMER/FETCH_CUSTOMERS'
export const FETCH_CUSTOMERS_SUCCESS = 'CUSTOMER/FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAILED = 'CUSTOMER/FETCH_CUSTOMERS_FAILED'

//CREATE OR UPDATE CUSTOMER
export const SAVE_CUSTOMER = 'CUSTOMER/SAVE_CUSTOMER'
export const SAVE_CUSTOMER_SUCCESS = 'CUSTOMER/SAVE_CUSTOMER_SUCCESS'
export const SAVE_CUSTOMER_FAILED = 'CUSTOMER/SAVE_CUSTOMER_FAILED'

//DELETE CUSTOMER
export const DELETE_CUSTOMER = 'CUSTOMER/DELETE_CUSTOMER'
export const DELETE_CUSTOMER_SUCCESS = 'CUSTOMER/DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAILED = 'CUSTOMER/DELETE_CUSTOMER_FAILED'

//SELECT CUSTOMER
export const SELECT_CUSTOMER = 'CUSTOMER/SELECT_CUSTOMER'