
//FETCH PRODUCT
export const FETCH_PRODUCTS = 'PRODUCT/FETCH_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'PRODUCT/FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILED = 'PRODUCT/FETCH_PRODUCTS_FAILED'

//CREATE OR UPDATE PRODUCT
export const SAVE_PRODUCT = 'PRODUCT/SAVE_PRODUCT'
export const SAVE_PRODUCT_SUCCESS = 'PRODUCT/SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_FAILED = 'PRODUCT/SAVE_PRODUCT_FAILED'

//DELETE PRODUCT
export const DELETE_PRODUCT = 'PRODUCT/DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'PRODUCT/DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILED = 'PRODUCT/DELETE_PRODUCT_FAILED'


//SELECT PRODUCT
export const SELECT_PRODUCT = 'PRODUCT/SELECT_PRODUCT'